version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  customer-service:
    image: ${REGISTRY:-service-one}/customer-service.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "my_postgres_db"
    container_name: customer-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: services/ServiceOne/ServiceOne.API/Dockerfile
    environment:
      - ConnectionString=Server=my_postgres_db;Port=5435;Database=employee;User Id=postgres;Password=postgres;
    networks:
      - dev

  my_postgres_db:
    image: postgres:latest
    container_name: customer_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  customer_data:

